### PR TITLE
Update npm and pypi installation commands in README docs

### PR DESCRIPTION
**Pull request by gnpaone**

### CODE REVIEW

**Comment by casey** [comment]
Looks good! But why the change from `pip` to `pipx`? Honestly I always forget the difference and I'm not sure why I used `pipx` in the first place.

**Comment by gnpaone** [comment]
It works with pip, pipx, rye, poetry, uv etc. pip is python inbuilt/default package installer, pipx needs to be installed first separately before using pipx cli commands I guess. For beginners to keep it simple I changed it to pip 🙂. pipx is fine too if you want to retain it

**Comment by casey** [comment]
I think I used `pipx` because on MacOS with Homebrew, `pip` doesn't work, and it's a common configuration. I changed it back to `pipx`. Otherwise looks good!

**Comment by gnpaone** [comment]
Okay 🙂

**Pull request merged**
