### PR TITLE
add --only flag in order to skip recipe dependencies

### LINKED ISSUE #1314: Skip dependencies
Oftentimes when I'm writing a new recipe, I'd like to re-run that task, and _only_ that task. I don't want the dependencies to run because they might take a long time, and I know they're up-to-date.

Another way to say this is: I'd like a way to run the recipes specified explicitly given on the command line, without any dependencies. One example I can find of this feature is [Fake's `--single-target` parameter](https://fake.build/core-targets.html).

I'm aware of several workarounds for this, but it would be very nice to have this feature baked in. To list a few of the workarounds, so that I might illustrate why I would like this feature:

1. Write the dependencies with something like [entr](http://eradman.com/entrproject/) so that they don't unnecessarily re-run, as suggested in #424. This requires me to focus on having very robust dependencies before focusing on the task that I'm actually trying to work on. Sometimes I'd rather write the whole tree quickly and then go back and add such niceties.
2. Split each of my recipes into two. One which is my recipe, containing no dependencies. The second recipe includes the dependencies and includes the first recipe as the final dependency. This makes the justfile much less readable, though. Not great to maintain.
3. Comment out the dependencies as I'm developing the task. This works until I forget to uncomment them when I'm done.

### PR DESCRIPTION
**Pull request by sousajo-cc**
using this flag one can just re-run only that task specified in the cmd line.

Closes: https://github.com/casey/just/issues/1314

### CODE REVIEW

**Comment by casey** [comment]
Nice! I'm curious, is this something that you personally needed? If so, what is the use-case?

I think that it would be better if this wasn't implemented as a option that takes an argument `just --only RECIPE`, where the `RECIPE` is an argument to the `--only` option. Instead, it should be a flag that doesn't take any arguments, but which, when used, causes `just` to skip running any dependencies that aren't explicitly mentioned on the command line. This would allow running it with multiple recipes, like `just --only foo bar`, as well as recipes that take arguments.

**Comment by sousajo-cc** [comment]
> Nice! I'm curious, is this something that you personally needed? If so, what is the use-case?
>
Hello :) Yeah I have kinda of complicated git workflow at work, and sometimes I just want to redo a specific recipe not the whole thing. 

> I think that it would be better if this wasn't implemented as a option that takes an argument `just --only RECIPE`, where the `RECIPE` is an argument to the `--only` option. Instead, it should be a flag that doesn't take any arguments, but which, when used, causes `just` to skip running any dependencies that aren't explicitly mentioned on the command line. This would allow running it with multiple recipes, like `just --only foo bar`, as well as recipes that take arguments.
>

That makes a lot of sense, now that you mention it, I will try to play with it a bit!

**Comment by sousajo-cc** [comment]
if that's ok @casey I will try to draft a couple of tests for it, and if you can get me a feedback on those would be great, so I'm sure that they can guide the implementation ^^

**Comment by casey** [comment]
> Hello :) Yeah I have kinda of complicated git workflow at work, and sometimes I just want to redo a specific recipe not the whole thing.

Okay good, I always like to make sure that features are actually going to be used!

> That makes a lot of sense, now that you mention it, I will try to play with it a bit!

Sounds good, give it a shot, and feel free to ask for help.

> if that's ok @casey I will try to draft a couple of tests for it, and if you can get me a feedback on those would be great, so I'm sure that they can guide the implementation ^^

That's a great idea, I think it's always good to write some tests first so you can get feedback and figure out exactly how the feature behaves, even if they fail.

**Comment by alexpovel** [comment]
Hi! I'm a potential user as well, I'd love this feature. In some sense, it's very antithetical to the idea of having a dependency graph in the first place. But as there are now _multiple_ (2!) people publicly voicing interest for this feature, perhaps we can let pragmatism overrule purity :^) 

That said, let me contribute a use case! In the .NET world, a (CI) workflow like [this one](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#using-the-net-starter-workflow) is customary:

```yaml
name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
```

However, a corresponding `Justfile` would have the dependencies as: `test: build` and `build: restore`. To test, we need to build, and to build, we need to restore any packages we depend on (`dotnet test` works by itself as well and will build and restore by itself, but this is `just`, so we're looking into making these steps explicit and separate!). `just test` then works beautifully locally, but in CI, it's beneficial to separate jobs into individual steps (or whatever the CI systems' lingo is). That allows us to debug quicker. A `just test` job might fail for a host of reasons, _not only_ due to failing tests. Package restoration might have failed. This wouldn't have good UI/UX visibility if `just test` were the only step in a job.

Similar ideas apply to [Python pipelines as well, for example](https://github.com/alexpovel/ancv/blob/8dc46cb83252eecc4031d1a7ab438a9548ed6f60/.github/workflows/publish.yml). A `test` requires installing the environment, but that in turn requires installing the tooling to set up our environment in the first place: `test: setup-environment`, and `setup-environment: install-poetry`, where `poetry` is an environment management tool. All the same ideas as described above apply.

Without a feature like `--only`, all this is hard to express, yet very desirable in CI. Maintaining separate, CI-specific jobs, which would each not specify any dependencies, is tedious.

I'm just getting into Rust myself, let me know if you're still working on this @sousajo-cc , else I can offer to chime in!

**Comment by casey** [comment]
This has gotten a little stale, feel free to update and re-open!

**Pull request closed without merging**
