### PR TITLE
Add doc for modules for `--list`

### PR DESCRIPTION
**Pull request by Spatenheinz**
PR for #2194.

### CODE REVIEW

**Review by casey — CHANGES_REQUESTED** [review]
Nice! Two things:

- This should have a test which shows that doc comments are printed, and that they're aligned.
- Since `Subcommand::format_doc` is only used inside of `Subcommand::list_module`, I would put it inside that function.

**Comment by Spatenheinz** [comment]
Ok I am a bit unsure why it shows other commits than mine as well. Maybe it is because I have rebased my fork in the meanwhile?

I think it should follow your requirements.
I also changed `/bin/echo` to `/usr/bin/env echo` in `tests/functions` as some of them where failing on for me on NixOS. using `/usr/bin/env` should be more universal. I just replaced all occurences of it for consistency. Let me know if you disagree.

**Comment by Spatenheinz** [comment]
Just noticed! I overwrote some of my changes while trying to fix the git repo.
Will have to reapply them.

**Review by casey — APPROVED** [review]
Looks good to me! I made some minor changes, mainly alphabetizing argument lists (when they get long enough, I just sort the argument by name instead of having some semantic order) and un-hiding the doc from the JSON serialization, and fixing the JSON tests.

The extra commits are expected, if you rebase onto a new version of master, you'll see those extra commits, but I ultimately always squash merge, so they get squashed away when they get merged to master.

**Pull request merged**
