### PR TITLE
Separates cross-platform managers into separate table

### PR DESCRIPTION
**Pull request by cskeeters**
As suggested in #1971.

### CODE REVIEW

**Comment by casey** [comment]
Looking at this, I think maybe it's better if we just put all the entries for `Various` at the top of the table, instead of splitting it into two , and maybe instead of `Various` call it `Cross-platform`. What do you think?

**Comment by cskeeters** [comment]
That's what I did.

**Comment by casey** [comment]
My suggestion is to keep a single table, but to put the cross-platform options at the top of that single table.

**Comment by cskeeters** [comment]
Oh I see.  Personally, I like the sparate table.  It's like two Hashmaps that have different keys.  It tells the user you have to check both maps; one for the package manager and one for the OS.  If you got rid of the OS column and ordered everything by package manager, that would be one thing, but then you'd loose some of the information you have about OS support.  That said, I think you should do what makes sense to you.

**Comment by casey** [comment]
Just based on personal preference, I think I like a single unified table best, mostly because I don't like too deeply nested headings.

**Comment by casey** [comment]
I wound up doing this in #2385, and I think you're right, multiples tables are probably best.

**Pull request closed without merging**
