### PR TITLE
Translate part of features to Chinese based on commit c87909c

### PR DESCRIPTION
**Pull request by hustcer**
Translate part of features to Chinese
It's really a long chapter

### CODE REVIEW

**Comment by casey** [comment]
真牛

**Comment by hustcer** [comment]
> invocation_directory() - Retrieves the absolute path to the current directory when just was invoked, before just changed it (chdir'd) prior to executing commands.

I'm not quite sure about this part "before just changed it (chdir'd) prior to executing commands" can you explain it with more detail?

**Comment by casey** [comment]
> I'm not quite sure about this part "before just changed it (chdir'd) prior to executing commands" can you explain it with more detail?

Yeah, definitely. So initially, the user invokes just in some directory, let's say `~/src/project/foo`. That's the initial working directory. Then just looks for the justfile, let's say it's in `~/src/project/justfile`, and changes the working directory to the directory that contains the justfile, in this case `~/src/project`. `invocation_directory()` returns the directory that just was invoked in, in this case ~/src/project/foo`.

**Comment by hustcer** [comment]
Ah, I see, thanks

**Pull request merged**
