### PR TITLE
Allow newlines when parsing recipes

### PR DESCRIPTION
**Pull request by neunenak**
Addresses https://github.com/casey/just/issues/1266

### CODE REVIEW

**Comment by casey** [comment]
Took a look at this, and I think that if this works, we should do it, even if it isn't a perfect solution. I looked at modifying the parser to switch between line-break sensitive and insensitive modes, and it seemed complicated.

**Comment by casey** [comment]
I updated this, and added a test, but I'm running into an issue where there's an indent before the parameter, and then no indent in the recipe body, which messes this up.

**Comment by laniakea64** [comment]
Given that the issue this PR aimed to resolve [has been fixed and closed](https://github.com/casey/just/issues/1266#issuecomment-1885988013), is this PR still needed?

Requiring the \ continuations here is better for human-readability of justfiles.  And this change would be hard to support properly in `vim-just` (if even possible?).

What would be the rationale for this change in current `just`?

**Comment by casey** [comment]
I think it's slightly nicer to not have to add `\`, but I agree that it's not necessary, now that there are `\` line continuations, so I'll go ahead and close this.

**Pull request closed without merging**
