### PR TITLE
add shebang support for 'cmd' script

### PR DESCRIPTION
**Pull request by pansila**

### CODE REVIEW

**Comment by casey** [comment]
Thanks for the PR! Is this necessary? I.e. does cmd.exe refuse to run scripts if they don't end with `.bat`?

**Comment by pansila** [comment]
Yes, I ran a script without '.bat' locally and see no output.

**Comment by casey** [comment]
Gotcha, thanks for confirming. It looks like there's a formatting error that's causing CI to fail.

You can run `cargo +nightly fmt --all` to fix it. (And `rustup install nightly` if you don't have it.)

**Comment by casey** [comment]
Merged, thank you for the contribution!

**Comment by casey** [comment]
Let me know if you'd like a release cut that includes this.

**Comment by pansila** [comment]
Yes, please make a release, I'm making some tests based on Just, thanks a lot.

**Comment by casey** [comment]
You bet, I just released v0.9.3, which includes this change. Binaries should appear on the release page shortly!

**Pull request merged**
