### PR TITLE
Fix recipe doc alignment in just --list

### PR DESCRIPTION
**Pull request by crdx**
`recipe.private` doesn't take into account recipes with the `[private]` attribute, so private recipes affect the alignment calculation of the the recipe docs. This causes them to align too far to the right.

Use `recipe.public()` instead which appears to be the canonical way of differentiating between public and private.

### CODE REVIEW

**Comment by casey** [comment]
Nice, good catch! Can you add a test for this?

**Comment by crdx** [comment]
Yep. Should it go in `tests/modules.rs` or a new file `tests/subcommand.rs`?

**Comment by crdx** [comment]
I went ahead and added it to `tests/modules.rs` as that felt like the right place. Verified it fails before the change and passes after.

**Comment by casey** [comment]
Whoops, sorry for forgetting about this. Looks good to me!

**Pull request merged**
