### PR TITLE
Eliminate lazy_static

### PR DESCRIPTION
**Pull request by camsteffen**
Just a little cleanup.

### CODE REVIEW

**Comment by camsteffen** [comment]
const Mutex::new requires Rust 1.63

**Comment by casey** [comment]
Thanks for the PR!

I like this change, but I don't think it's worth bumping the MSRV so aggressively. 1.65 was released on Nov. 3, so a little over a month ago. Just doesn't have a formal MSRV policy, but I think I'd like to support at least the last couple of Rust releases.

**Comment by camsteffen** [comment]
It could be 1.63.

**Comment by casey** [comment]
I'm rethinking this. I've tried to be conservative with my MSRV policy, but I don't have a super clear memory for why. I think I want to revisit the reasons for that conservatism, come up with a concrete policy (e.g. support last two Rust releases) and then we can figure out hat new policy allows merging this. Hang tight!

**Comment by camsteffen** [comment]
I would think MSRV doesn't matter much since this isn't a library?

**Comment by casey** [comment]
Just is packaged for a number of distros, and if their version of rust lags behind Just's MSRV, they won't be able to package it, and users won't be able to build it from source. I'm not sure if this is a problem in practice though.

**Comment by casey** [comment]
Based on surveying the internet, it seems like a conservative MSRV isn't super important for binary crates, so I decided to just switch MSRV to stable.

Merged, with a bunch of fixes for latest clippy.

Thanks for the PR!

**Pull request merged**
