### PR TITLE
Add `workdir` setting

### PR DESCRIPTION
**Pull request by nyurik**
Implement #2273 - an ability to set workdir for the entire justfile

### CODE REVIEW

**Comment by casey** [comment]
Nice! Check out `Recipe::working_directory`. If `self.change_directory()` is true, first use the `workdir` setting, and if it isn't present, Use the existing logic.

**Comment by nyurik** [comment]
thx @casey, seems to work, ready for review

**Comment by casey** [comment]
Nice! I did some refactoring, and renamed the setting `working-directory` for clarity, since i try to avoid too many abbreviations. We could eventually also allow `working-dir` as an alias.

This also made me realize that there's a bug! backticks do not execute in the correct directory if they're in a submodule. I'll fix that in another PR.

**Comment by nyurik** [comment]
thx!  Are you sure you want a long `working-dir` when you already have a short `tempdir` ?

**Comment by casey** [comment]
I think so, just because I commonly hear `tempdir`, but people usually say `working directory` or `working dir`, and `workdir` feels a little less common.

**Comment by nyurik** [comment]
:shrug: your call. I searched github for code matches:
* [workdir](https://github.com/search?q=%22workdir%22&type=code) - 3.5M
* [working directory](https://github.com/search?q=%22working+directory%22&type=code) - 2.7M

P.S. `working directory` mostly seem to show up in documentation, but `workdir` tend to be a lot in the actual code

**Pull request merged**
