### PR TITLE
Add usage gif to README

### LINKED ISSUE #916: Make GIF for readme
- write a justfile
- list recipes
- run a recipe

### PR DESCRIPTION
**Pull request by Celeo**
Fixes #916

Like we briefly discussed in the issue; asciinema is a nice tool, but it's not suitable for embedding in READMEs. I'm using [asciinema/asciicast2gif](https://github.com/asciinema/asciicast2gif) to convert to a gif. Is this in line with what you're looking for? Where do you want it in the README?

If you could do me a favor, toss the "hacktoberfest" label on the issue and PR. ;)

### CODE REVIEW

**Comment by casey** [comment]
> Like we briefly discussed in the issue; asciinema is a nice tool, but it's not suitable for embedding in READMEs. I'm using [asciinema/asciicast2gif](https://github.com/asciinema/asciicast2gif) to convert to a gif. Is this in line with what you're looking for?

This looks good! I think the font should be larger, and the image size smaller, similar to the existing screenshot. Also, ideally, it should be like the current still image, with an editor on the left and a shell on the right. If you use tmux, you can create a vertical split. I think it'll be easier for people to absorb without having to remember what's in the justfile while the commands are running.

> Where do you want it in the README?

I think at the top is good, it can replace the still image.

> If you could do me a favor, toss the "hacktoberfest" label on the issue and PR. ;)

Done!

**Comment by Celeo** [comment]
I've dropped the usage of asciinema completely in favor of autohotkey'ing the output and recording with GifCam - gives me a lot more control.

**Comment by casey** [comment]
Nice! One thing I was thinking about is that it would be nice to be able to easily update the GIF in the future. One way to do this would be to script the terminal interactions, so that the script can be edited, and the GIF recreated without having to do it manually. If this sounds fun/interesting, then give it a shot, but if it's more effort than you want to put into this PR, then I'd rather not hold up this PR and just get something in.

**Comment by casey** [comment]
I have a GIF scripting setup for another project that could be adapted.

The [justfile](https://github.com/casey/intermodal/blob/master/justfile#L100) kicks things off, and the demo script that generates keystrokes is [here](https://github.com/casey/intermodal/blob/master/bin/demo/src/main.rs).

**Comment by Celeo** [comment]
Oh nice!

I'm not sure that'll allow for jumping into vim and editing the file; I could have it right the content of the justfile onto the console passed to an `echo -ne "..." > justfile` I imagine. Not as nice given the lack of syntax highlighting, but I don't know another way around it.

**Comment by casey** [comment]
> I'm not sure that'll allow for jumping into vim and editing the file

You might be able to by starting vim, echoing an `i` into standard input to start insert mode, then echoing the contents of the file, then `<esc>`, using `nvr` or something to send the keystrokes.

**Comment by Celeo** [comment]
Sorry, I've looked around, but can't find what "nvr" is.

**Comment by casey** [comment]
Ah, sorry, it's this thing: https://github.com/mhinz/neovim-remote

**Comment by Celeo** [comment]
Thanks! Prompted me to actually go and get neovim installed, and I played around with the demo program in intermodal. Unfortunately I still have problems with asciicast2gif.

Starting neovim in one terminal and echo'ing things to it with nvr from another works great. Sending nvr commands from demo program also works, though the command that it's actually printing to the console (this is a _different_ console than where neovim is running), shows the nvr commands; I'll have to clean that up. I suppose I could open nvim in the terminal, and have the nvr commands run in a thread? They wouldn't be printed, and from the point of view of the viewer, they'd just see uniform typing into nvim. Then the last nvr command would, like you mentioned, save and close nvim, and then drop back to the "main" terminal window and type the remainder of the commands like they're typed for the intermodal demo.

**Comment by casey** [comment]
> Sending nvr commands from demo program also works, though the command that it's actually printing to the console (this is a _different_ console than where neovim is running), shows the nvr commands; I'll have to clean that up. I suppose I could open nvim in the terminal, and have the nvr commands run in a thread?

I'm not sure if I understand the exact setup. What exactly is going wrong?

**Comment by Celeo** [comment]
Alright, made progress. The demo binary loads up neovim, fires nvr commands from a thread, and then resumes the main terminal to show the just commands. This is filling out the justfile (roughly) by line rather than individual characters; let me know if that's a change you want. Additionally, although asciinema records and plays back without error,there's text overlapping between what the "user" is typing into the neovim window and the text that shows on startup.

**Comment by casey** [comment]
Nice! Can you add a rendered demo.gif so I can take a look?

Edit: I mean add it to the files in the PR, since I assume we'll want to commit it anyways.

**Comment by Celeo** [comment]
Sorry for the delay in getting this resolved! I'd love to, but that's where I'm having problems, unfortunately. I'm attaching the generated demo.json file here; could you please see if asciicast2gif works for you?

[demo.zip](https://github.com/casey/just/files/7316133/demo.zip)

```plain
asciicast2gif -S4 tmp/demo.json www/demo.gif
==> Loading tmp/demo.json...
==> Spawning PhantomJS renderer...
==> Generating frame screenshots...
==> Combining 46 screenshots into GIF file...
gifsicle:<stdin>: empty file
/usr/lib/node_modules/asciicast2gif/main.js:697
Qe)}function ep(a){try{var b=a[0];return b.h?b.h(a):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,Yo(a[6]),b;throw c;}}function fp(a,b,c){c=Zo(c,dp(function(c){a[2]=c;a[1]=b;return ep(a)}));return r(c)?(a[2]=Nb(c),a[1]=b,dj):null}function gp(a,b){a=a[6];null!=b&&a.Dc(null,b,dp(function(){return function(){return null}}(a)));Yo(a);return a}
                                                                                                   ^

Error: Command failed: convert -loop 0 -delay 6 /tmp/tmp.e4ylxyK0MN/0.png -delay 6 /tmp/tmp.e4ylxyK0MN/1.png -delay 6 /tmp/tmp.e4ylxyK0MN/2.png -delay 6 /tmp/tmp.e4ylxyK0MN/3.png -delay 6 /tmp/tmp.e4ylxyK0MN/4.png -delay 13 /tmp/tmp.e4ylxyK0MN/5.png -delay 140 /tmp/tmp.e4ylxyK0MN/6.png -delay 133 /tmp/tmp.e4ylxyK0MN/7.png -delay 139 /tmp/tmp.e4ylxyK0MN/8.png -delay 133 /tmp/tmp.e4ylxyK0MN/9.png -delay 139 /tmp/tmp.e4ylxyK0MN/10.png -delay 133 /tmp/tmp.e4ylxyK0MN/11.png -delay 140 /tmp/tmp.e4ylxyK0MN/12.png -delay 133 /tmp/tmp.e4ylxyK0MN/13.png -delay 140 /tmp/tmp.e4ylxyK0MN/14.png -delay 6 /tmp/tmp.e4ylxyK0MN/15.png -delay 6 /tmp/tmp.e4ylxyK0MN/16.png -delay 6 /tmp/tmp.e4ylxyK0MN/17.png -delay 6 /tmp/tmp.e4ylxyK0MN/18.png -delay 6 /tmp/tmp.e4ylxyK0MN/19.png -delay 6 /tmp/tmp.e4ylxyK0MN/20.png -delay 6 /tmp/tmp.e4ylxyK0MN/21.png -delay 6 /tmp/tmp.e4ylxyK0MN/22.png -delay 6 /tmp/tmp.e4ylxyK0MN/23.png -delay 6 /tmp/tmp.e4ylxyK0MN/24.png -delay 26 /tmp/tmp.e4ylxyK0MN/25.png -delay 6 /tmp/tmp.e4ylxyK0MN/26.png -delay 46 /tmp/tmp.e4ylxyK0MN/27.png -delay 6 /tmp/tmp.e4ylxyK0MN/28.png -delay 6 /tmp/tmp.e4ylxyK0MN/29.png -delay 6 /tmp/tmp.e4ylxyK0MN/30.png -delay 6 /tmp/tmp.e4ylxyK0MN/31.png -delay 6 /tmp/tmp.e4ylxyK0MN/32.png -delay 6 /tmp/tmp.e4ylxyK0MN/33.png -delay 6 /tmp/tmp.e4ylxyK0MN/34.png -delay 6 /tmp/tmp.e4ylxyK0MN/35.png -delay 26 /tmp/tmp.e4ylxyK0MN/36.png -delay 6 /tmp/tmp.e4ylxyK0MN/37.png -delay 6 /tmp/tmp.e4ylxyK0MN/38.png -delay 53 /tmp/tmp.e4ylxyK0MN/39.png -delay 6 /tmp/tmp.e4ylxyK0MN/40.png -delay 6 /tmp/tmp.e4ylxyK0MN/41.png -delay 6 /tmp/tmp.e4ylxyK0MN/42.png -delay 6 /tmp/tmp.e4ylxyK0MN/43.png -delay 26 /tmp/tmp.e4ylxyK0MN/44.png -delay 100 /tmp/tmp.e4ylxyK0MN/45.png -layers Optimize gif:- | gifsicle -k 64 -O2 -Okeep-empty --lossy=80 -o www/demo.gif -
gifsicle:<stdin>: empty file

    at checkExecSyncError (child_process.js:640:11)
    at Object.execSync (child_process.js:676:15)
    at Dp (/usr/lib/node_modules/asciicast2gif/main.js:708:246)
    at /usr/lib/node_modules/asciicast2gif/main.js:713:178
    at Function.b [as h] (/usr/lib/node_modules/asciicast2gif/main.js:709:287)
    at ep (/usr/lib/node_modules/asciicast2gif/main.js:697:48)
    at /usr/lib/node_modules/asciicast2gif/main.js:697:193
    at /usr/lib/node_modules/asciicast2gif/main.js:689:264
    at Immediate.Po (/usr/lib/node_modules/asciicast2gif/main.js:685:331)
    at processImmediate (internal/timers.js:462:21) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(29) [Uint8Array] [
      103, 105, 102, 115, 105,  99, 108,
      101,  58,  60, 115, 116, 100, 105,
      110,  62,  58,  32, 101, 109, 112,
      116, 121,  32, 102, 105, 108, 101,
       10
    ]
  ],
  pid: 8467,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(29) [Uint8Array] [
    103, 105, 102, 115, 105,  99, 108,
    101,  58,  60, 115, 116, 100, 105,
    110,  62,  58,  32, 101, 109, 112,
    116, 121,  32, 102, 105, 108, 101,
     10
  ]
}
error: Recipe `demo-render` failed on line 220 with exit code 1
```

**Comment by casey** [comment]
Sorry for taking so long to respond!

This actually worked on my machine, I downloaded demo.json and ran `asciicast2gif -S4 demo.json demo.gif`.

I also have `gifsicle` and `imagemagick` installed, which from looking at the output, might be dependencies.

demo

**Comment by Celeo** [comment]
Thank you! 

IMO:

1. It's still a little small
2. I don't like the "jumpiness" of the file editor

I know I can fix that second point; I'll do that first.

**Comment by casey** [comment]
> Thank you!

You're welcome!

> IMO:
> 
> 1. It's still a little small
> 2. I don't like the "jumpiness" of the file editor
> 
> I know I can fix that second point; I'll do that first.

Agreed on both points, and sounds good. I think it might be possible to fix the first point just by making the terminal smaller. (Or the font bigger? I'm not sure how asciinema works.)

**Comment by casey** [comment]
Whoops, I fat-fingered the close button.

**Comment by Celeo** [comment]
Updated the demo program; it's more natural now, though a touch slower than I'd like (overheard of forking off commands, I'm assuming).

Unfortunately I'm _still_ not able to use the renderer despite also having those dependencies installed. Could I trouble you to run this through it again?

[demo.zip](https://github.com/casey/just/files/7343160/demo.zip)

**Comment by casey** [comment]
Sweet, looking smoother. What error message are you getting, and what asciicast2gif command are you running?

demo

**Comment by Celeo** [comment]
Thanks! I blew my terminal font size _way_ up when recording, so I wonder if it's an asciinema setting to focus in a bit? Not sure either.

I'm running `just demo` in the project root, and getting [this](https://textbin.net/raw/dvbwhxzgsm).

```sh
❯ paru -Q | grep -e gifsicle -e imagemagick
gifsicle 1.93-1
imagemagick 7.1.0.10-1
```

**Comment by casey** [comment]
Very weird. What about the `convert` command? It's bundled with imagemagick, so you should have it, but maybe it's missing. Maybe also check that you have enough free disk space, and maybe look at RAM usage too, since it definitely took a long time on my machine, so it seemed like maybe it was disk or RAM intensive.

At the very worst though, feel free to keep sending me the demos as JSON files, and I can just render the final product on my machine.

**Comment by Celeo** [comment]
I checked RAM usage, and you're right. I increased the memory allotment for the VM and added a swapfile, and the gif converter takes all 14GB of RAM and 10GB of swapfile before crashing. It's likely that something's just going very wrong, but it could be that you have a beast of a machine. ^_^

**Comment by casey** [comment]
> I checked RAM usage, and you're right. I increased the memory allotment for the VM and added a swapfile, and the gif converter takes all 14GB of RAM and 10GB of swapfile before crashing. It's likely that something's just going very wrong, but it could be that you have a beast of a machine. ^_^

My machine is pretty old, but it does have 16GiB of ram, so that might be the difference. I think it has something to do with the GIF compression step. You might be able to run it at a lower resolution while you're testing, and then I can render it on high resolution on my machine.

**Comment by Celeo** [comment]
Made some progress and got the converter to work. It was 50% crazy RAM usage, 50% PEBKAC.

Anyhow, updating PR. I don't know why the playback is "eating" the commands that are typed into the terminal.

**Comment by casey** [comment]
> Made some progress and got the converter to work. It was 50% crazy RAM usage, 50% PEBKAC.

Nice! What fixed it?

> Anyhow, updating PR. I don't know why the playback is "eating" the commands that are typed into the terminal.

Lookin good!

I think it'll look best if every character appears in the editor at the same speed, i.e. no pauses after newlines.

**Comment by Celeo** [comment]
I certainly needed to feed the converter more RAM, but I also was trying to output to "www/demo.gif" when I hadn't created that "www" directory. :| 

> I think it'll look best if every character appears in the editor at the same speed, i.e. no pauses after newlines.

Sure thing!

**Comment by Celeo** [comment]
Apologies; forgot to push that change >.<

**Comment by casey** [comment]
No worries!

Just rendered it, and there are some issues. There's a weird pause after commands, like `just lis` is fast, but then the `t` and newline take a while. Also, the justfile contents winds up being commented out, I think because I have a vim plugin that auto-inserts comments if you hit return on al in a line with a comment. We should figure out a way to run nvim with a no config, and with a copy of the syntax highlighting plugin.


demo

**Comment by casey** [comment]
I just pushed a couple of minor changes to the justfile:

- I replaces tabs with spaces
- I removed and re-created tmp before the demo, since it wasn't getting created

**Comment by Celeo** [comment]
Ah dang, forgot about that. My nvim was doing the same but I fiddled with it enough to, well, _not_ do that.

**Pull request closed without merging**
