### PR TITLE
add homebrew to readme

### PR DESCRIPTION
**Pull request by imevro**
found formula in homebrew, thought it will be useful to be reflected in readme

 https://formulae.brew.sh/formula/just

### CODE REVIEW

**Comment by casey** [comment]
If I'm not mistaken, homebrew is already listed in the readme: https://github.com/casey/just/?tab=readme-ov-file#packages

**Comment by imevro** [comment]
ah my bad

thanks!

**Comment by cskeeters** [comment]
Funny, I just made the same change and almost submitted a pull request for it.  I wonder if the maintainers have considered having a separate table at the top of the packages section for cross-platform package managers?  Breaking it into two tables would help users conceptually understand that they need to check two spots.  As it is, I searched for my OS and then concluded it wasn't listed.  Apparently, I'm not the only one.

**Comment by casey** [comment]
I wouldn't mind a PR which splits the table into two, with cross-OS options in the first table, and the OS-specific options in the second.

**Pull request closed without merging**
