### PR TITLE
Update README to clarify state of vim-polyglot's packaging of vim-just

### PR DESCRIPTION
**Pull request by laniakea64**
Context: https://github.com/NoahTheDuke/vim-just/issues/25#issuecomment-1627750120

### CODE REVIEW

**Comment by laniakea64** [comment]
Hi @casey do you need anything else from me in order to review and merge this?  Thanks - and thank you for `just`, it makes a much simpler and nicer workflow than other means of running dev tasks! :+1:

**Comment by laniakea64** [comment]
> Hi @casey do you need anything else from me in order to review and merge this?

Would appreciate this answer, especially since this is my first time contributing to improve `just` documentation, so I don't yet have a good sense of what's wanted in such pull requests.  Thank you for your review.

**Comment by laniakea64** [comment]
Maybe few things weren't clear from the context link:

 - The author of this PR (me) is co-maintainer of `vim-just` since March 2023.

 - Regarding [my original comment about this part of `just` documentation](https://github.com/NoahTheDuke/vim-just/issues/25#issuecomment-1633295834), note that the difference between `vim-just` and `vim-polyglot`'s justfile support is already substantial.  There have been major changes in `vim-just` since June 2021: current `vim-just` supports highlighting all syntaxes of `just` 1.14.0 (and our just-prerelease branch additionally supports all syntaxes added since then up to [this `just` revision](https://github.com/casey/just/tree/63ed00ff78055777e1664b5031374dcec4634e87)), plus many bug fixes and other enhancements.

 - There are other areas `just` documentation could be improved (including documenting pre-release syntaxes, but some other things too).  After this PR is reviewed & merged, I'm hoping to make another PR containing those improvements.

**Comment by casey** [comment]
Thanks for the PR! If `vim-polyglot` is unmaintained, then we should probably just remove it from the readme. Want to remove it instead of adding a note?

**Review by casey — CHANGES_REQUESTED** [review]
See comment.

**Comment by laniakea64** [comment]
> If `vim-polyglot` is unmaintained, then we should probably just remove it from the readme.

Done.  Thanks for your input :slightly_smiling_face:

**Review by casey — APPROVED** [review]
Thanks, looks good!

**Comment by casey** [comment]
Also, can you update to the latest master?

**Comment by casey** [comment]
Merged, thank you!

**Pull request merged**
