### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by casey** [comment]
Thanks for the PR! A lot of these changes are good, but for empty vecs, I prefer Vec::new(), can you revert those changes?

**Comment by adamnemecek** [comment]
Sure ill do it tomorrow. Isnt vec much cleaner?

**Comment by casey** [comment]
It's just a personal preference. I think `vec![]` is fine, but I like to avoid macros where possible.

**Comment by casey** [comment]
Nice, looks good, merged!

**Pull request merged**
