### PR TITLE
Support "::" in Bash completions

### PR DESCRIPTION
**Pull request by crdx**
Modules use `::` as the separator, which is considered a wordbreak character in Bash. This means they can't be completed by default, as colon is considered the end of a completion.

The (very) bad way to solve this is by globally modifying `COMP_WORDBREAKS` to remove the colon character. Not only is this bad because it can have unintended side-effects, but git's completion script actually adds the colon back if it detects it's not present.

So Bash made available the `_get_comp_words_by_ref` and `__ltrim_colon_completions` functions for this purpose. They're not present on every platform, in which case we fall back to the original method.

### CODE REVIEW

**Comment by crdx** [comment]
... oh. 

That completion file is generated by clap. Right.

**Comment by crdx** [comment]
Gonna be fun making those changes using only search/replacements in `BASH_COMPLETION_REPLACEMENTS`.

**Comment by crdx** [comment]
Should be good now.

**Comment by casey** [comment]
Nice, LGTM!

**Pull request merged**
