### PR TITLE
Add a replace function that supports regex

### LINKED ISSUE #1389: Add a replace function that supports regex
The current `replace(s, from, to)` function doesn't seem to support regex. I think it would be helpful to also have a `replace_regex(s, from, to)` for more complex replacements.

### PR DESCRIPTION
**Pull request by miles170**
Add `replace_regex(s, from, to)` that supports replacing text using regular expressions.

Closes #1389.

### CODE REVIEW

**Comment by ianpittwood** [comment]
LGTM! Thanks for taking this on!

**Comment by casey** [comment]
Thanks for this, and sorry I've been so slow to review it! Can you add a test for the error case? I want to make sure the error message looks good. If the regex crate's error message doesn't show the original regex, we should include that as well.

**Comment by miles170** [comment]
There is a typo in the README. (regec -> regex)

**Comment by casey** [comment]
Good catch! Fixing here: #1409.

Tweaked the argument names and added an entry in the readme. I also removed the error prefix, I think the underlying error is probably descriptive enough. Thank you for the PR!

**Pull request merged**
