### PR TITLE
Implement the private attribute for assignments

### LINKED ISSUE #2299: Allow defining private variables
Often, I need to define variables that are built from a smaller set of fundamental settings/variables. It would be useful to allow `[private]` to work on variables such that they can't be defined by the user of the script. Alternatively, the `_` prefix could also be used such that `just --variables` avoids listing them.

Happy to work on a PR if this is something that will be accepted

### PR DESCRIPTION
**Pull request by adsnaider**
This PR fixes https://github.com/casey/just/issues/2299. When a variable is specified as `[private]` or is named with `_*` the variable will be hidden from `just --variables` and forbidden from being overridden. I purposefully didn't change the behavior of the evaluator on private variables since it's likely useful to be able to view the values of private variables for debugging & introspection.

### CODE REVIEW

**Review by casey — CHANGES_REQUESTED** [review]
The `[private]` attribute on recipes doesn't prevent running private them, only listing them, and I'm inclined to think the `[private]` variable attribute should similar, i.e., only prevent listing them, but still allow overriding them.

**Comment by casey** [comment]
I would also filter them out of `--evaluate`. We can think about some kind of `--all` flag in a follow-up PR, which un-hides them. (`--all` should probably also allow listing all recipes, including private recipes)

**Comment by adsnaider** [comment]
I believe this is ready again. Haven't implemented the `--all` flag but the other changes should now be working properly and as you point out that flag can be added later

**Review by casey — CHANGES_REQUESTED** [review]
Sorry I missed this the first time! I would remove the `allow-private-variables` setting, since I think an `--all` flag, which can be added later, is more useful and general.

**Comment by adsnaider** [comment]
Ah sure, I assumed that would be a backwards-incompatible change

**Comment by laniakea64** [comment]
> Ah sure, I assumed that would be a backwards-incompatible change

Using the `[private]` attribute on variables is backwards-compatible, since it's an error to do that in current `just`, so it won't change behavior of any working justfiles.  So no need for a setting for that.

But wouldn't making all underscore-prefixed variables private be backwards-incompatible, and therefore _that_ aspect _would_ need an opt-in setting?

**Comment by adsnaider** [comment]
@laniakea64 Yeah, that's what I thought. I could take out the `_` prefix for private variables :shrug:

**Comment by casey** [comment]
It could be argued either way, but I think making variables private if they start with `_` is probably fine. It won't actually break any justfiles, just remove those variables from the output of `just --evaluate` and `just --variables`, which are, I think, mostly for human consumption.

**Comment by adsnaider** [comment]
> Sorry I missed this the first time! I would remove the `allow-private-variables` setting, since I think an `--all` flag, which can be added later, is more useful and general.

Removed the setting @casey

**Review by casey — APPROVED** [review]
LGTM!

**Comment by casey** [comment]
Available in 1.35.0, just released: https://github.com/casey/just/releases/tag/1.35.0

**Pull request merged**
