### PR TITLE
Fix README typos

### PR DESCRIPTION
**Pull request by akuhnregnier**
This fixes some minor typos in the documentation.

### CODE REVIEW

**Comment by casey** [comment]
This fixes one type, but introduces a new one.

**Comment by akuhnregnier** [comment]
That is on purpose, since the sentence where the typo is introduced is meant to illustrate `just`'s ability to catch typos.
At least that's how I understand it. If that's not correct, I will revert that change of course.

**Comment by casey** [comment]
@akuhnregnier Whoops! Of course you're right. LGTM.

**Comment by casey** [comment]
Actually, I think that sentence is referring to unwanted space-splitting, not typos. It's a bit unclear though, I'll rewrite it.

**Pull request merged**
