### PR TITLE
Support shell()

### PR DESCRIPTION
**Pull request by gyreas**
This PR add support for the `shell()`, which expands to the output of running its given command. 

Example:
```just
set shell := ["fish", "-c"]
v := shell("
set p $argv
for i in $p
	echo "$i"
end
",  "Nightmares", "on", "Elms", "Street")

_:
  @echo "{{ v }}"
```
output:
```console
Nightmares
on
Elms
Street
```

### CODE REVIEW

**Comment by casey** [comment]
This seems really nice! What do you think about getting rid of the `name` argument for now? Since a lot of uses of this function won't use it, it seems unfortunate to force users to pass an additional dummy argument if they want to pass arguments. I'd like to enable it in the future with a dedicated named argument syntax, i.e., `shell(CMD, name=NAME, ARGS)`, which is generally useful and can be done in a future PR.

**Comment by casey** [comment]
Also, this should be documented in the readme.

**Comment by gyreas** [comment]
Alright. I clean stuff up, I think I have a solution to remove that inconvenience. Thanks

**Comment by casey** [comment]
I think this should be refactored to use the same code as `Evaluator::run_backtick`. `run_backtick` does a few additional things, like setting the working directory, exporting environment variables, and the destination of stderr.

To make this easier, I just landed #2048, which gets rid of `FunctionContext` and instead just passes the `Evaluator`, since all fields on `FunctionContext` are just taken from `Evaluator` anyways.

The signature of `run_backtick` can be changed to something like:

```
fn run_command(&self, command: &str, args: &[String], token: Option<&Token<'src>>) -> RunResult<'src, String> {
```

Which produces an `Error::Backtick` when `token` is present, and an `Error::FunctionCall` when it isn't.

**Comment by casey** [comment]
Nice, LGTM!

**Comment by gyreas** [comment]
Thank you!

**Comment by casey** [comment]
Thank you! `shell()` is a great addition!

**Pull request merged**
