### PR TITLE
Add bash completion for snap

### PR DESCRIPTION
**Pull request by albertodonato**
Also switches the snap to core22

### CODE REVIEW

**Comment by casey** [comment]
I don't really have the ability to test changes to the snapcraft.yaml file, since I don't have an ubuntu machine at the moment, so just to confirm, you tested this and it works?

**Comment by albertodonato** [comment]
Yes, I tested with a locally built snap and it works for me.

**Comment by casey** [comment]
Good enough for me! Thank you!

**Comment by albertodonato** [comment]
Out of curiosity, are you currently publishing the snap manually? AFAICS the last build in the store is quite old

**Comment by casey** [comment]
I am. Or at least I was 😅 I really need to publish a new version.

**Comment by albertodonato** [comment]
FWIW it's possible to set up automation (through the snapcraft site) for the edge channel so that the snap is published on changes to the master branch.

**Comment by casey** [comment]
I tried publishing a new version, but it was pretty annoying, so I gave up and instead removed instructions for installing via the snap in the readme #2070 😅 I think that `just` may actually now be available in Ubuntu 24.04 using `apt`.

**Comment by zekefast** [comment]
May be it could be useful to tests changes like this.

There is a project called [distobox](https://github.com/89luca89/distrobox) which allows to spin up different distributions very quickly. I found it very useful for myself. May be you will too.

**Pull request merged**
