### PR TITLE
Allow multiline shebangs in scripts

### PR DESCRIPTION
**Pull request by vkstrm**
Fix for issue #2024, allowing multiline shebangs, most importantly for use with Nix scripts, I don't know if they are relevant anywhere else.

Manual testing with Nix works for me, and I think error line numbers are retained correctly. The test added is a bit fake (just reads it like a shebang and shell like a comment), but a realistic integration test would require adding Nix to the dependencies which maybe isn't a good idea.

First time contributing, thank you for any feedback!

### CODE REVIEW

**Review by casey — CHANGES_REQUESTED** [review]
Thanks for the PR! It looks like this code will trigger no matter where in the recipe body the shebang line is. Instead, it should only trigger for the first contiguous shebang lines, and then treat shebang lines after the first non-shebang line normally.

**Comment by vkstrm** [comment]
f20f493f53c441c3e6b7de90cc22a603a50aa95b A suggestion how to do that. Looks a bit more messy, but won't look at shebangs after the ones following the first line. The middle iteration is annoying since it still needs to handle a non-shebang line so that it is added correctly. The last one is cleaner though.

**Comment by laniakea64** [comment]
> Looks a bit more messy, 

FWIW there is also https://github.com/casey/just/pull/2073 which started to attempt a different approach to implement multi-line shebang functionality.  If avoiding messy-looking code is important, might that other PR suggest some way to improve this?

**Comment by vkstrm** [comment]
> > Looks a bit more messy,
> 
> FWIW there is also #2073 which started to attempt a different approach to implement multi-line shebang functionality. If avoiding messy-looking code is important, might that other PR suggest some way to improve this?

I did look at that first but gave it a go myself since it seems it wasn't being worked on. I guess it depends on how you look at it if that solutions is more appropriate, if the Shebang struct is interested in more than just the actual real shebang? I can see how collecting them there and then using them in script() could be done. If you think that is better I can try.

**Comment by laniakea64** [comment]
I'm not `just` dev so not sure what's better.  If I were making this patch less messy-looking I'd make the iterator `.peekable()` and change your middle iteration to something like
```rust
        // Any shebang line that follows the first should also be at the top
        while let Some((line, evaluated)) = iter.by_ref().peek() {
          if !line.is_shebang() {
            break;
          }

          script.push_str(evaluated);
          script.push('\n');
          n += 1;
          iter.next();
        }
```
This avoids duplicating the line-number-matching code and is more concise.

Tried this locally and it passes `cargo test` here.

**Comment by vkstrm** [comment]
Thank you for the suggestion! I tried it with peekable, it helped a bit.
Also moved everything out of the Command arm because it didn't do anything different anymore.
2112a3e0e00f1a0c99fb37f8538695cef795ace7

**Review by casey — APPROVED** [review]
LGTM! I simplified it slightly to count the number of shebang lines ahead of time, to avoid needing a peekable iterator, and then just skipping however many shebang lines we processed later.

**Pull request merged**
