### PR TITLE
Fix issues reported by clippy

### PR DESCRIPTION
**Pull request by neunenak**
Fixes every issue reported by running vanilla-configuration `cargo clippy`.

### CODE REVIEW

**Comment by casey** [comment]
How can I get these errors? When I run `cargo clippy` it doesn't complain.

**Comment by neunenak** [comment]
Huh, I just realized, I had my default toolchain set to nightly, not stable. It looks like these are all lints that are only reported on nightly clippy.

**Comment by neunenak** [comment]
I just tested it and this branch compiles and passes all tests on stable as well.

**Comment by casey** [comment]
Okay, sweet. I was worried I had something weird going on with the config.

**Comment by casey** [comment]
Actually, looking at these, they all look like reasonable fixes, so why not merge them.

**Pull request merged**
